import Header from "@/components/Header";
import "./globals.scss";
import { Jost } from "next/font/google";
import Providers from "@/components/Providers";
import { Metadata } from "next";

const inter = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next 13 App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
