import PostsList from "@/components/Posts/PostsList";
import { GetStaticProps, Metadata } from "next";

export const metadata: Metadata = {
  title: "Posts | Next 13 App",
  description: "Generated by create next app",
}; 

export default function Home() {
  return (
    <div>
      <PostsList />
    </div>
  )
}


