import TodosList from "@/components/TodosList";
import { Metadata } from "next";
import { FC } from "react";
import React from "react";

export const metadata: Metadata = {
  title: "Todos | Next 13 App",
  description: "Generated by create next app",
}; 

const Todos: FC = () => {
  return (
    <div>
      <TodosList />
    </div>
  );
};

export default Todos;