import FavoriteList from "@/components/FavoriteList";
import { Metadata } from "next";
import React, { FC } from "react";

export const metadata: Metadata = {
  title: "Favorites | Next 13 App",
  description: "Generated by create next app",
};

const Favorites: FC = () => {
  return <FavoriteList />;
};

export default Favorites;
