import AlbumsList from '@/components/Albums/AlbumsList';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: "Albums | Next 13 App",
  description: "Generated by create next app",
}; 

const Albums = () => {
  return (
    <div>
      <AlbumsList />
    </div>
  );
};

export default Albums;